# Generated by Django 4.2.5 on 2023-12-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsk1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='section',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='section',
        ),
        migrations.RemoveField(
            model_name='project',
            name='section',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='section',
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('photography', 'Photography'), ('logo', 'Logo'), ('graphics', 'Graphics'), ('advertising', 'Advertising'), ('fashion', 'Fashion')], default='all', max_length=20),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
