# Generated by Django 4.2.5 on 2023-12-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsk1', '0002_creator_remove_contact_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tsk1/static/tsk1/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tsk1/static/tsk1/img/portfolio/'),
        ),
    ]
