# Generated by Django 4.2.5 on 2024-01-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsk1', '0004_remove_contact_message_remove_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/portfolio/'),
        ),
    ]
